commit:
  changelogs:
    - label: "commit.changelog"
      destination: "./CHANGELOG.md"

  changetypes:
    - label: "commit.type.add"
      name: "add"
    - label: "commit.type.chg"
      name: "chg"
    - label: "commit.type.fix"
      name: "fix"
    - label: "commit.type.dep"
      name: "dep"

  includes:
    - ruby-gem
    - ruby-rspec
    - ruby-standard
    - oss
    - git

  externals:
    - repo: "metabahn/commit-templates"
      private: true

git:
  ignore:
    - "tmp"

license:
  slug: mpl
  name: "MPL-2.0"

project:
  slug: "b3bm"
  description: "Base62 for Ruby."

  author:
    name: "Bryan Powell"
    email: "bryan@metabahn.com"
    homepage: "https://github.com/metabahn/b3bm/"

  copyright:
    attribution: "Metabahn"
    year: 2021

ruby:
  gem:
    path: "b3bm"
    namespace: "B3bm"
    extra: |-2
        spec.files = Dir["CHANGELOG.md", "README.md", "LICENSE", "lib/**/*"]
        spec.require_path = "lib"
